language: objective-c
osx_image: xcode8.2
xcode_project: ViewControllerTestable.xcodeproj
xcode_scheme:
    - ViewControllerTestable
script:
    - xcodebuild clean test -sdk iphonesimulator -scheme ViewControllerTestable -project ViewControllerTestable.xcodeproj -destination 'id=22FA2149-1241-469C-BF6D-462D3837DB72' -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO
after_success:
    - bash <(curl -s https://codecov.io/bash)
