language: objective-c
osx_image: xcode8.2
xcode_project: ViewControllerTestable.xcodeproj
xcode_scheme:
    - ViewControllerTestable
    - ViewControllerTestableMock
script:
    - xcodebuild clean test -sdk iphonesimulator -scheme ViewControllerTestable -project ViewControllerTestable.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 7' -enableCodeCoverage YES
    - xcodebuild clean test -sdk iphonesimulator -scheme ViewControllerTestableMock -project ViewControllerTestable.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 7' -enableCodeCoverage YES
after_success:
    - bash <(curl -s https://codecov.io/bash)
